all-Win:
	@echo "For Windows:"
	@echo "[arch] indicates that environmental variable arch={i386} is accepted"

prepare-Win:
	$(choco) install cmake
	$(choco) install 7zip
	$(choco) install ruby

uninstall-Win: 
	$(remove) $(installroot)

