# hack
build/sparc/$(facter_)/._.hack: | build/sparc/$(facter_)
	-ln -s /opt/pl-build-tools/$(arch)/bin/$(target)-ar /opt/pl-build-tools/$(arch)/bin/ar
	touch $@

include projects/facter/Makefile.SunOS-i386
