# hack
build/sparc/$(cfacter_)/._.hack: | build/sparc/$(cfacter_)
	-ln -s /opt/pl-build-tools/$(arch)/bin/$(target)-ar /opt/pl-build-tools/$(arch)/bin/ar
	touch $@

include projects/cfacter/Makefile.SunOS-i386
