export YAMLCPP_ROOT=$(installroot)

fetched/$(yamlcpp_).tar.gz:
	$(wget) 'https://yaml-cpp.googlecode.com/files/$(yamlcpp_).tar.gz'
	mv $(yamlcpp_).tar.gz $(@D)

build/$(arch)/$(yamlcpp_)/._.config: source/$(yamlcpp_)/._.patch $(cmake) install/$(arch)/$(boost_)/._.install
	(cd $(@D) && $(cmakecmd) \
		  -DCMAKE_INSTALL_PREFIX:PATH=$(prefix) \
		  -DBUILD_SHARED_LIBS=ON \
		  -DYAML_CPP_BUILD_TOOLS=0 $(rootdir)/source/$(yamlcpp_) \
	) $(t) $@.log
	touch $@
