# config rules for binutils
build/$(arch)/$(binutils_)/._.config: source/$(binutils_)/._.patch
	(cd $(@D) && env $(nativeenv) $(rootdir)/source/$(binutils_)/configure \
			--target=$(target) \
			--prefix=$(prefix) \
			$(sysroot) \
			--disable-nls \
			-v \
	) $(t) $@.log
	touch $@

